name: Immigration Short Avatar

on:
  schedule:
    - cron: '33 */14 1 * *' 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python on the runner
      with:
        python-version: '3.x'  # Specify the Python version (e.g., 3.6, 3.7, etc.)
        
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev
        python -m pip install --upgrade pip
        python -m pip install requests
        python -m pip install moviepy==1.0.3
        python -m pip install Pillow
        python -m pip install google
        python -m pip install google_auth_oauthlib
        python -m pip install google-api-python-client
        python -m pip install facebook-sdk 
        python -m pip install matplotlib



    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: Ar-Sa/SMbot
        token: ${{ secrets.SMBOTPAT }} # `GH_PAT` is a secret that contains your PAT
        path: SMbot

    - name: Run  Script
      run: |
        echo "Current Working Directory: $PWD"
        ls -l | grep '^d' | awk '{print $9}'
        cd SMbot/ytpy/py
        ls -l | grep '^d' | awk '{print $9}'
        python video-ImmigrationShortAvatar.py

    - name: Commit changes
      run: |
        cd SMbot

        git config --global user.email "toarun4u@gmail.com"
        git config --global user.name "gitcommit.acc"

        git pull

        FILES=$(find . -type f \( -name "*.txt" -o -name "*.csv" -o -name "*.json" \))

        if [ -z "$FILES" ]; then
          echo "No allowed files found"
          exit 0
        fi

        git add $FILES

        if git diff --cached --quiet; then
          echo "No changes detected"
        else
          git commit -m "Auto commit-from git action"
          git push
        fi
